// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lmojxjryxcrctwwcxqui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxtb2p4anJ5eGNyY3R3d2N4cXVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3OTIwNzgsImV4cCI6MjA2MjM2ODA3OH0.G43m9r-ihOguuD5oU4JJLth1lN2mqjoge8dRLbvAD-0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);